id: P009644
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG09213
  title: སྨན་གཞུང་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    63df72c7c1e54772b26ba70540fef2bc:
      image_group_id: I00KG09362
      title: ''
      volume_number: 1
      total_pages: 530
      base_file: v001.txt
