id: I9C4F9ECA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T18:52:46+00:00'
last_modified: '2022-06-08T12:31:47.319243+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG09213
  title: སྨན་གཞུང་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    736F:
      image_group_id: I00KG09362
      title: ''
      total_pages: 530
      order: 1
      base_file: 736F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
