id: I9C4F9ECA
legacy_id: P009644
ocr_import_info:
  bdrc_scan_id: W00KG09213
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T18:49:34'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T12:29:48.279410+00:00'
last_modified: 2022-08-29 20:30:25.680290
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG09213
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00KG09213
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྨན་གཞུང་ཕྱོགས་བསྒྲིགས།
statistics:
  ocr_word_mean_confidence_index: 0.8091101092784776
  ocr_word_median_confidence_index: 0.8999999761581421
quality: null
bases:
  I00KG09362:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG09362
      total_pages: 530
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG09362.txt
    statistics:
      ocr_word_median_confidence_index: 0.8999999761581421
      ocr_word_mean_confidence_index: 0.8091101092784776
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
